version: "3.9"

services:
  job-service:
    image: job-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
  postgres:
    image: postgres
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/job
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

