version: "3.9"

services:
  job-service:
    image: "job-service"
    networks:
      - jobs-net
    hostname: job-service
    #ports:
    #  - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/job
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ITINERARY_SERVICE_URL=http://itinerary-service:9080


  api-gateway:
    image: "api-gateway"
    networks:
      - jobs-net
    ports:
      - "8085:8085"
    depends_on:
      - job-service
    environment:
      - JOB_SERVICE_URL=http://job-service:8082
      - AUTH_SERVICE_URL=http://user-authorization-service:8090


  oauth-service:
    networks:
      - jobs-net
    image: "oauth-service"
    #hostname: oauth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/job
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  user-authorization-service:
    networks:
      - jobs-net
    image: "user-authorization-service"
    depends_on:
      - postgres
    hostname: user-authorization-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/job
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend-jobs:
    networks:
      - jobs-net
    image: "frontend-jobs"
    ports:
      - "80:3000"
    environment:
      - REACT_APP_OAUTH_SERVICE_URL=http://localhost:8080

  itinerary:
    hostname: itinerary-service
    image: "itinerary"
    networks:
      - jobs-net
    ports:
      - "9080:9080"

  libretranslate:
    image: "libretranslate"
    networks:
      - jobs-net
    ports:
      - "5000:5000"
    environment:
      - CORS_ORIGIN_WHITELIST=http://0.0.0.0:*



  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=job
    networks:
      - jobs-net
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data


networks:
  jobs-net:

